<?php
// $Id: feeds_ui.module,v 1.6 2009/09/21 14:55:47 alexb Exp $
/**
 * @file
 */

/**
 * Implementation of hook_help().
 */
function feeds_ui_help($path, $arg) {
  switch ($path) {
    case 'admin/build/feeds':
      $output = '<p>'. t('Configure one or more feeds to import content into Drupal. You can use these feed configurations directly here or - if you attach them to a content type - simply by creating a node from that content type.') .'</p>';
      return $output;
    case 'admin/content/feeds':
      $output = '<p>'. t('Import content into Drupal.') .'</p>';
      return $output;
  }
}

/**
 * Implementation of hook_menu().
 */
function feeds_ui_menu() {
  $items = array();
  $items['admin/content/feeds'] = array(
    'title' => 'Feeds',
    'page callback' => 'feeds_ui_content_overview',
    'access arguments' => array('use feeds'),
    'file' => 'feeds_ui.admin.inc',
  );
  $items['admin/content/feeds/%feeds'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_content_feed', 3),
    'access arguments' => array('use feeds'),
    'file' => 'feeds_ui.admin.inc',
  );
  $items['admin/build/feeds'] = array(
    'title' => 'Feeds',
    'page callback' => 'feeds_ui_build_overview',
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
  );
  $items['admin/build/feeds/create'] = array(
    'title' => t('Create configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_build_create_form'),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/feeds/edit/%feeds'] = array(
    'title callback' => 'feed_ui_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_build_edit_form', 4),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/feeds/edit/%feeds/edit'] = array(
    'title' => t('Basic'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/build/feeds/edit/%feeds/plugins'] = array(
    'title' => t('Plugins'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_build_plugin_form', 4),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/build/feeds/edit/%feeds/map'] = array(
    'title' => t('Mapping'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_build_mapping_form', 4),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  $items['admin/build/feeds/map-remove/%feeds'] = array(
    'page callback' => 'feeds_ui_build_mapping_remove',
    'page arguments' => array(4),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/feeds/delete/%feeds'] = array(
    'title' => t('Create configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_build_delete_form', 4),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function feeds_ui_theme() {
  return array(
    'feeds_ui_build_mapping_form' => array(
      'arguments' => array('form'),
      'file' => 'feeds_ui.admin.inc',
    ),
  );
}

/**
 * Title callback.
 */
function feed_ui_title($feed) {
  return t('Edit !feed', array('!feed' => $feed->getId()));
}